{% set name = "picologging" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/picologging-{{ version }}.tar.gz
  sha256: c0e263937a7fad3d3ec91c2311356f7ff699f605e960fac3eae409ff5b2f330a

build:
  skip: true  # [(py<37) or (python_impl == 'pypy')]
  script:
    - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - setuptools >=42
  host:
    - cmake >=3.18
    - ninja
    - pip
    - python
    - scikit-build >=0.13
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - picologging
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/microsoft/picologging
  summary: A fast and lightweight logging library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
